version: '3.9'

name: mail-service

services:
  api:
    container_name: mail-service-api
    ports:
      - 127.0.0.1:0:80
    environment:
      FLASK_APP: wsgi.py
      SA_CREDS_LOCATION: sa_creds.json
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - .:/app
    networks:
      - nw

networks:
  nw:
    name: "nw"