version: '3.9'

name: mail-service

services:

  ################
  # MAIL SERVICE #
  ################

  api:
    container_name: mail-service-api
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      FLASK_APP: wsgi.py
      SA_CREDS_LOCATION: sa_creds.json
    volumes:
      - .:/app
    ports:
      - 127.0.0.1:0:80