version: '3.9'
services:
  api:
    container_name: mail-service
    ports:
      - 8080:5000 # map: local:container
    # env_file:
    #   - .env
    # environment:
    #   DB_HOST: db
    #   DB_PORT: 5432
    #   DB_NAME: cvshare
    #   DB_USER: postgres
    #   DB_PASSWORD: postgresPassword
    #   TOKEN_TTL: 2000
    #   JWT_PRIVATE_KEY: verysecretjwtkey
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - .:/app
